package com.example.candyfisher.utils;

public enum Candies {
    PINK_GUMMYBEAR,
    PURPLE_GUMMYBEAR,
    GREEN_GUMMYBEAR,
    BLUE_GUMMYBEAR,
    YELLOW_GUMMYBEAR,
    GREEN_LOLLIPOP,
    YELLOW_LOLLIPOP,
    PINK_LOLLIPOP,
    ORANGE_LOLLIPOP,
    CHOCOLATE_SWIRL,
    BLACK_AND_WHITE_CHOCOLATE,
    STRIPED_CHOCOLATE,
    CRISP_CHOCOLATE,
    RED_WRAPPER,
    BLUE_WRAPPER,
    GREEN_WRAPPER,
    BIG_RED_WRAPPER,
    BIG_PURPLE_WRAPPER,
    POLKA_HEART,
    SWIRLY_HEART,
    PINK_AND_BLUE_CANDY_COIN,
    PINK_AND_YELLOW_CANDY_COIN,
    GREEN_CANDY_COIN
}
